# Generated by Django 5.2.4 on 2025-08-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_cnh', models.CharField(help_text='Ex: A, B, C, D, E, AD', max_length=4)),
                ('data_validade_cnh', models.DateField()),
                ('data_emissao_cnh', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuário associado ao condutor', on_delete=django.db.models.deletion.CASCADE, related_name='condutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'condutor',
                'verbose_name_plural': 'condutores',
            },
        ),
    ]
