# Generated by Django 5.2.4 on 2025-08-15 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_condutores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='condutor',
            name='categoria_cnh',
            field=models.CharField(help_text='Categoria da CNH do condutor. Exemplos: A, B, C, D, E, AD.', max_length=4),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização das informações do condutor.'),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro do condutor foi criado.'),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='data_emissao_cnh',
            field=models.DateField(help_text='Data de emissão da CNH (formato AAAA-MM-DD).'),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='data_validade_cnh',
            field=models.DateField(help_text='Data de validade da CNH (formato AAAA-MM-DD).'),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='usuario',
            field=models.OneToOneField(help_text='Usuário associado a este condutor.', on_delete=django.db.models.deletion.CASCADE, related_name='condutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
