# Generated by Django 5.2.4 on 2025-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence.', related_name='usuario_custom_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='usuario_custom_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
