# Generated by Django 5.2.4 on 2025-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_remove_usuariocustom_is_staff_usuariocustom_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
