# Generated by Django 5.2.4 on 2025-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_usuariocustom_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='data_nascimento',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='sexo',
            field=models.CharField(choices=[(
                'M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
    ]
