# Generated by Django 5.2.4 on 2025-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0004_usuariocustom_data_nascimento_usuariocustom_sexo'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='cpf',
            field=models.CharField(help_text='CPF do usuário, apenas números (11 dígitos).', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='data_nascimento',
            field=models.DateField(help_text='Data de nascimento do usuário (formato AAAA-MM-DD).'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='email',
            field=models.EmailField(help_text='Endereço de e-mail único para contato e login.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se a conta do usuário está ativa.'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica se o usuário pode acessar a área administrativa.'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indica se o usuário possui todas as permissões do sistema.'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='matricula',
            field=models.CharField(blank=True, help_text='Identificador único do usuário no sistema. É gerado automaticamente se não for informado.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do usuário.', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', help_text='Sexo do usuário: Masculino (M), Feminino (F) ou Outro (O).', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato. Pode incluir DDD.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas atribuídas a este usuário.', related_name='usuario_custom_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
