# Generated by Django 5.2.4 on 2025-08-15 14:36

import app_veiculos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoTaxiVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico_veiculo', models.CharField(default=app_veiculos.models.gerar_identificador_unico, editable=False, help_text='Código único para identificação do veículo (alfanumérico de 8 caracteres)', max_length=8, unique=True, verbose_name='Identificador Único do Veículo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(max_length=20, unique=True, verbose_name='RENAVAM')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('anoFabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('anoLimiteFabricacao', models.PositiveIntegerField(verbose_name='Ano Limite de Fabricação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_veiculos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mototáxi',
                'verbose_name_plural': 'Mototáxis',
            },
        ),
        migrations.CreateModel(
            name='TaxiVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico_veiculo', models.CharField(default=app_veiculos.models.gerar_identificador_unico, editable=False, help_text='Código único para identificação do veículo (alfanumérico de 8 caracteres)', max_length=8, unique=True, verbose_name='Identificador Único do Veículo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(max_length=20, unique=True, verbose_name='RENAVAM')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('anoFabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('anoLimiteFabricacao', models.PositiveIntegerField(verbose_name='Ano Limite de Fabricação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_veiculos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Táxi',
                'verbose_name_plural': 'Táxis',
            },
        ),
        migrations.CreateModel(
            name='TransporteMunicipalVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico_veiculo', models.CharField(default=app_veiculos.models.gerar_identificador_unico, editable=False, help_text='Código único para identificação do veículo (alfanumérico de 8 caracteres)', max_length=8, unique=True, verbose_name='Identificador Único do Veículo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(max_length=20, unique=True, verbose_name='RENAVAM')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('anoFabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('anoLimiteFabricacao', models.PositiveIntegerField(verbose_name='Ano Limite de Fabricação')),
                ('linha', models.CharField(help_text='Identificação da linha ou rota do transporte municipal', max_length=50, verbose_name='Linha / Rota')),
                ('capacidade', models.PositiveIntegerField(help_text='Número máximo de passageiros', verbose_name='Capacidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_veiculos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transporte Municipal',
                'verbose_name_plural': 'Transportes Municipais',
            },
        ),
    ]
