# Generated by Django 5.2.4 on 2025-08-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculos', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerIdentificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID do veículo')),
                ('arquivo_banner', models.ImageField(help_text='Arquivo do banner com QR Code', upload_to='banners_identificacao/')),
                ('qr_url', models.URLField(help_text='URL codificada no QR Code', max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do banner')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o banner está ativo')),
                ('content_type', models.ForeignKey(help_text='Tipo do modelo do veículo', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Banner de Identificação',
                'verbose_name_plural': 'Banners de Identificação',
                'db_table': 'banner_identificacao',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
