# Generated by Django 5.2.4 on 2025-08-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculos', '0005_make_identificador_required'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneridentificacao',
            name='content_type',
            field=models.ForeignKey(editable=False, help_text='Tipo do modelo do veículo', on_delete=django.db.models.deletion.CASCADE, related_name='banners_identificacao', to='contenttypes.contenttype'),
        ),
    ]
