# Generated by Django 5.2.4 on 2025-08-22 13:27

import app_veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculos', '0006_alter_banneridentificacao_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneridentificacao',
            name='arquivo_banner',
            field=models.ImageField(help_text='Arquivo do banner com QR Code', upload_to=app_veiculos.models.upload_banner_to),
        ),
    ]
